import type { BlockDef } from '../core/types';
import raw from './blocks.json';
import textureColors from './texture-colors.json';
import textureManifest from './textures.json';

/**
 * Block catalog (136 full + 52 half + 49 stairs = 237 types).
 * IDs, display names, and pillar_axis presence are cross-checked against Mojang's
 * official bedrock-samples (mojang-blocks.json / en_US.lang / ja_JP.lang).
 * Regenerate with `npm run gen-blocks` (requires network access).
 * Unrecognized derivatives get a "possibly missing" warning at generation time.
 *
 * **The catalog doesn't hold representative colors.** Color is a texture property, so
 * `texture-colors.json` (per-texture average color, generated by the final stage of
 * `npm run fetch-textures`) is the source of truth, joined in here via `textures.json`.
 * Baking color into the catalog would create a cycle — "can't fetch textures without the
 * catalog, can't build the catalog without colors" — blocking new blocks from being added
 * (review, #137).
 */

const COLORS = textureColors as Record<string, string>;
const MANIFEST = textureManifest as Record<string, { side: string; top?: string }>;

/** The side face represents the block visually. Only fall back to the top face when the side has no color */
function colorOf(id: string): string {
  const entry = MANIFEST[id];
  const file = [entry?.side, entry?.top].find((f) => f !== undefined && f in COLORS);
  if (file === undefined) {
    throw new Error(`Cannot resolve a representative color for block: ${id} (run npm run fetch-textures)`);
  }
  return COLORS[file]!;
}

export const CATALOG: BlockDef[] = (raw as Omit<BlockDef, 'color'>[]).map((block) => ({
  ...block,
  color: colorOf(block.id),
}));
